# Django(CVE-2016-9014) Debug模式下任意Host可访问

## 详情

[Django News & Events](https://www.djangoproject.com/weblog/2016/nov/01/security-releases/#s-cve-2016-9014-dns-rebinding-vulnerability-when-debug-true)虽然称这个漏洞为DNS Rebinding，但是个人觉得这个漏洞和传统意义上的DNS重绑定漏洞是有区别的。

这个漏洞主要在于，在Debug模式下`settings.ALLOWED_HOSTS`是无效的。即使http headers中带有的host不在`settings.ALLOWED_HOSTS`之内也能正常访问站点。Django中获取的http header host字段的方法是: `get_host`(/django/http/request.py),这次的漏洞也出在这个函数里:

        def get_host(self):
            """Return the HTTP host using the environment or request headers."""
            host = self._get_raw_host()

            # There is no hostname validation when DEBUG=True
            if settings.DEBUG:
                return host

            domain, port = split_domain_port(host)
            if domain and validate_host(domain, settings.ALLOWED_HOSTS):
                return host
            else:
                msg = "Invalid HTTP_HOST header: %r." % host
                if domain:
                    msg += " You may need to add %r to ALLOWED_HOSTS." % domain
                else:
                    msg += " The domain name provided is not valid according to RFC 1034/1035."
                raise DisallowedHost(msg)

当host不在ALLOWED_HOSTS范围内的时候(`validate_host(domain, settings.ALLOWED_HOSTS)`)，该函数会raise一个DisallowedHost异常，但是如果在debug模式下，他会直接返回host，不会进行`validate_host`的判断。Django因为这个疏忽发出了一个CVE，对于国内的大部分厂商来说这并不是一个漏洞。

对`ALLOWED_HOSTS`的验证在Django每一个request&response中都会做，但是为了更直观，我弄了一个最简单页面。

        def DNS_rebinding_in_get_host(request):
            return HttpResponse("hello world")

在debug模式下，你把任意域名绑定到该站点都可以正常访问(非DEBUG模式下，如果你没有设置`ALLOWED_HOSTS`django会抛出一个`CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.`错误。)。我们用burpsuite做一下测试：

修复前，任意host不会影响到网站访问：

![](http://ww1.sinaimg.cn/large/005y7Ba5gy1ff1dkr4gvkj31p40j276g.jpg)

修复后,host不正确会抛出异常:

![](http://ww1.sinaimg.cn/large/005y7Ba5gy1ff1dtw5yctj31rk0omn09.jpg)

![](http://ww1.sinaimg.cn/large/005y7Ba5gy1ff1dtpd4dyj31t40zincc.jpg)


## 修复

        allowed_hosts = settings.ALLOWED_HOSTS
        if settings.DEBUG and not allowed_hosts:
            allowed_hosts = ['localhost', '127.0.0.1', '[::1]']

修复之后的django在debug模式下，如果没有设置`settings.ALLOWED_HOSTS`,默认接受三个host的请求`['localhost', '127.0.0.1', '[::1]']`,除了这三个之外的请求都会抛出异常。

![](http://ww1.sinaimg.cn/large/005y7Ba5gy1ff1dd11ctuj31tc0ncdm5.jpg)
